### ISSUE TITLE
Can't run convert

### ISSUE THREAD

**Issue by neshala** [cmer/cointracking_to_bitcointax#1]
I was able to do` bundle install` and got all dependencies, but when I run

`./convert`

I have this error output:

> Retrieving trades from CoinTracking...
> Traceback (most recent call last):
> 	5: from ./convert:4:in `<main>'
> 	4: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
> 	3: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
> 	2: from /home/crypto/htdocs/ui/include/cointracking_to_bitcointax-master/lib/main.rb:173:in `<top (required)>'
> 	1: from /home/crypto/htdocs/ui/include/cointracking_to_bitcointax-master/lib/main.rb:139:in `run'
> /home/crypto/htdocs/ui/include/cointracking_to_bitcointax-master/lib/main.rb:29:in `retrieve_trades_data': uninitialized constant CoinTracking (NameError)
> [crypto@cm-cryptotwins ~/htdocs/ui/include/cointracking_to_bitcointax-master]$

Also configured config.yml with valid API keys, but still not working.
Not sure if and where I need to set uninitialized constant CoinTracking 

Is this script out of date or what could be the issue?

**Comment by cmer** [comment]
You're right. It should be fixed now.

**Comment by neshala** [comment]
Thanks for the quick fix, but it appears that we have a new issue now:

`Traceback (most recent call last):
./convert:4:in `<main>': uninitialized constant Bundler (NameError)`

I am not familiar with Ruby programming, and I really appreciate your help to make this working.

**Comment by cmer** [comment]
run:

```
gem install bundler
bundle install
./convert
```

**Comment by neshala** [comment]
Ok i did as you suggested but still not working. Here is full output from my terminal:

[crypto@cm-cryptotwins ~/htdocs/ui/include/cointracking_to_bitcointax-master]$ gem install bundler
Successfully installed bundler-2.0.2
Parsing documentation for bundler-2.0.2
Done installing documentation for bundler after 3 seconds
1 gem installed
[crypto@cm-cryptotwins ~/htdocs/ui/include/cointracking_to_bitcointax-master]$ bundle install
Using concurrent-ruby 1.1.5
Using i18n 1.6.0
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using zeitwerk 2.1.9
Using activesupport 6.0.0
Using activemodel 6.0.0
Using activerecord 6.0.0
Using attribute_normalizer 1.2.0
Using bundler 1.17.2
Using byebug 11.0.1
Using mime-types-data 3.2019.0331
Using mime-types 3.2.2
Using multi_xml 0.6.0
Using httparty 0.17.0
Using coin_tracking 1.0.1
Using rounding 1.0.1
Using sqlite3 1.4.1
Bundle complete! 6 Gemfile dependencies, 19 gems now installed.
Bundled gems are installed into `./vendor/bundle`
[crypto@cm-cryptotwins ~/htdocs/ui/include/cointracking_to_bitcointax-master]$ ./convert
Traceback (most recent call last):
./convert:4:in `<main>': uninitialized constant Bundler (NameError)
[crypto@cm-cryptotwins ~/htdocs/ui/include/cointracking_to_bitcointax-master]$


Still have this error: uninitialized constant Bundler (NameError)

**Comment by neshala** [comment]
Ok i think that i found the solution.

I added:
`require 'bundler'`
before 
`Bundler.require(:default)`

And it works now. Cheers.
